### ISSUE TITLE
Ranks/scores should also be specified in settings

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-horserace#19]
Currently every visualisation is being defaulted on "Ranks", with the possibility to switch to "Scores". I think it's more important to be able to switch and save this inside the settings, and possibly making the controls available to the end-user.

For example: [polling data](https://public.flourish.studio/visualisation/1433/) and [football tables](https://public.flourish.studio/visualisation/1434/) you usually want to show as scores, but currently defaults to ranks. Especially in case of sports tables, as they use a different tiebreak system (taking into account goal difference etc).

**Comment by theduncanclark** [comment]
The setting is still there, it's just under "default view" rather than "axes", which wasn't very intuitive (felt more like somewhere you'd specify axis labels etc). If you didn't see it maybe that section should be further up? 

Agree it wouldn't hurt to have a setting to hide or show the ranks switch. Is that what you meant?

Good point about goal difference. Maybe we should support that one day.

**Comment by daanlouter** [comment]
Ah, missed that one. Will add a "Hide button"-setting.

Goal difference is probably a rabbit hole, as it's not a consistent system across different sports. Plus you'll then have to support cases where points and goal difference are both equal, etc.
